apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-stack-dev
  namespace: argocd
  labels:
    architect-lab.io/source: self
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-architect-lab
  source:
    repoURL: REPLACE_WITH_REPO_URL
    targetRevision: main
    path: platform/apps/demo-stack/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
