apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
  labels:
    architect-lab.io/source: self
spec:
  project: platform
  source:
    repoURL: REPLACE_WITH_REPO_URL
    targetRevision: main
    path: platform/system/gateway-api
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
