apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
spec:
  project: platform
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 41.0.2
    helm:
      valuesObject:
        deployment:
          replicas: 1
        providers:
          kubernetesCRD:
            enabled: false
          kubernetesIngress:
            enabled: false
          kubernetesGateway:
            enabled: true
            statusAddress:
              ip: 62.84.187.187
              service:
                enabled: false
        gateway:
          enabled: false
        gatewayClass:
          enabled: true
          name: traefik
        service:
          enabled: false
        ports:
          web:
            hostPort: 80
          websecure:
            hostPort: 443
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
