apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: food-delivery
  namespace: argocd
spec:
  description: Food Delivery application resources.
  sourceRepos:
    - https://github.com/rongvangc/k8s-architect-lab.git
  destinations:
    - namespace: apps-dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Service
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: gateway.networking.k8s.io
      kind: Gateway
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
