all:
  children:
    kubernetes:
      children:
        control_plane:
          hosts:
            control-plane-1:
              ansible_host: 62.84.187.187
              ansible_user: root
              node_ip: 62.84.187.187