apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-dev
resources:
  - ../../base
  - namespace.yaml
patches:
  - target:
      kind: ConfigMap
      name: api-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: dev
      - op: replace
        path: /data/DATABASE_NAME
        value: architect_lab_dev
images:
  - name: ghcr.io/example/food-delivery-api
    newName: ghcr.io/rongvangc/food-delivery-api
    newTag: dev
  - name: ghcr.io/example/food-delivery-web
    newName: ghcr.io/rongvangc/food-delivery-web
    newTag: dev
