---
kubernetes_minor: v1.36
kubernetes_pod_cidr: 10.245.0.0/16
kubernetes_service_cidr: 10.96.0.0/12
kubernetes_api_endpoint: 62.84.187.187
environment_name: development

calico_version: v3.32.1
calico_operator_sha256: f18e073794207d372606bc3ea6f8fd73972f86d6828f4ba666dfe0d4aa8ab07f

argocd_version: v3.4.5
argocd_install_sha256: cdf6758b489d25641c2a1fd835642543aaa64fe530867d0136a83ddf3dafe456
gitops_bootstrap_enabled: true
argocd_expose_nodeport: true
argocd_image_updater_enabled: true
argocd_image_updater_git_username: rongvangc

# Repository used by the DEV Argo CD root Application.
git_repo_url: https://github.com/rongvangc/k8s-architect-lab.git

application_namespace: apps-dev
postgres_user: architect
postgres_database: architect_lab_dev
