apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
  - ../../base
  - namespace.yaml
images:
  - name: ghcr.io/example/k8s-architect-lab-api
    newName: ghcr.io/REPLACE_WITH_GITHUB_USER/k8s-architect-lab-api
    newTag: "0.1.0"
  - name: ghcr.io/example/k8s-architect-lab-web
    newName: ghcr.io/REPLACE_WITH_GITHUB_USER/k8s-architect-lab-web
    newTag: "0.1.0"
