apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects/default-project.yaml
  - projects/platform-project.yaml
  - projects/food-delivery-project.yaml
  - applications/gateway-api.yaml
  - applications/local-path.yaml
  - applications/metrics-server.yaml
  - applications/cert-manager.yaml
  - applications/traefik.yaml
  - applications/food-delivery-dev.yaml
